SELECT employee_id,name,salary,salary*2+10 as rahat FROM employee where job='Waiter';
SELECT name,salary,salary+ salary- 1000 * 50 / 100 
FROM employee 
where job ='Cook';
select * from employee where manager_id is null;
//null is not avabibale kisu nai not 0
select employee_id id,name as "Employee Name" from employee;
select name || job as rahat from employee;
select name ||' '|| 'is'||' '||'a'||' '|| job as "details" from employee;
select distinct manager_id from employee;
/////////////////////////////////////////////////////////
SELECT * FROM EMP WHERE JOB IS NULL OR JOB=' ';
SELECT ENAME,SAL FROM EMP WHERE SAL> (SELECT AVG(SAL) FROM EMP);

SELECT * FROM EMP WHERE JOB = 'MANAGER' OR COMM IS NULL;
SELECT * FROM EMP WHERE JOB IN('MANAGER','SALESMAN') AND ENAME LIKE 'M%N' AND MOD(SAL,500)=0 AND TRIM(TO_CHAR(HIREDATE,'DY')) NOT IN ('SAT','SUN') AND SAL*1.1>2500;
SELECT * 
FROM EMP
WHERE 
JOB<> 'MANAGER' 
AND MGR IS NOT NULL 
AND SAL>50000 
AND SAL>(SELECT AVG(SAL) FROM EMP) 
AND MOD(TO_NUMBER(TO_CHAR(HIREDATE,'MM')),2)=0; 

SELECT ENAME FROM EMP WHERE ENAME LIKE '%S%' 
AND COMM IS NOT NULL 
AND COMM>4000
AND DEPTNO IN (10,30)
ORDER BY COMM DESC;
SELECT * FROM EMP WHERE  SAL BETWEEN 30000 AND 80000 AND HIREDATE ='10-APR-16';
SELECT * FROM EMP WHERE  SAL BETWEEN 30000 AND 80000 AND EXTRACT(YEAR FROM HIREDATE)>2016;
SELECT * FROM EMP WHERE JOB='SALESMAN'AND COMM <SAL+SAL*0.2 ORDER BY SAL ASC;
SELECT * FROM EMP WHERE EXTRACT(MONTH FROM HIREDATE) IN (6,7,8) AND SAL BETWEEN 30000 AND 70000;
SELECT * FROM EMP WHERE JOB<>'MANAGER'AND SAL>80000;
SELECT * FROM EMP WHERE JOB<>'MANAGER'AND SAL>80000;
SELECT SAL+COMM GROSS FROM EMP WHERE JOB='SALESMAN';
SELECT DISTINCT JOB FROM EMP;
SELECT SAL*12 "ANNUAL SAL" ,ENAME,SAL FROM EMP ORDER BY "ANNUAL SAL"  DESC,SAL ASC,ENAME DESC;
SELECT ENAME FROM EMP WHERE JOB IN('MANAGER','SALESMAN') AND ENAME LIKE'M%N' AND SAL+SAL*0.1>2500 AND JOB <> 'MANAGER' ORDER BY SAL DESC;
SELECT HIREDATE FROM EMP WHERE HIREDATE LIKE '%SEP%';
SELECT HIREDATE FROM EMP WHERE HIREDATE LIKE '%18';
