SELECT employee_id,name,salary,salary*2+10 as rahat FROM employee where job='Waiter';
SELECT name,salary,salary+ salary- 1000 * 50 / 100 
FROM employee 
where job ='Cook';
select * from employee where manager_id is null;
//null is not avabibale kisu nai not 0
select employee_id id,name as "Employee Name" from employee;
select name || job as rahat from employee;
select name ||' '|| 'is'||' '||'a'||' '|| job as "details" from employee;
select distinct manager_id from employee;
/////////////////////////////////////////////////////////
SELECT * FROM EMP WHERE JOB IS NULL OR JOB=' ';
SELECT ENAME,SAL FROM EMP WHERE SAL> (SELECT AVG(SAL) FROM EMP);

SELECT * FROM EMP WHERE JOB = 'MANAGER' OR COMM IS NULL;
SELECT * FROM EMP WHERE JOB IN('MANAGER','SALESMAN') AND ENAME LIKE 'M%N' AND MOD(SAL,500)=0 AND TRIM(TO_CHAR(HIREDATE,'DY')) NOT IN ('SAT','SUN') AND SAL*1.1>2500;
SELECT * 
FROM EMP
WHERE 
JOB<> 'MANAGER' 
AND MGR IS NOT NULL 
AND SAL>50000 
AND SAL>(SELECT AVG(SAL) FROM EMP) 
AND MOD(TO_NUMBER(TO_CHAR(HIREDATE,'MM')),2)=0; 

SELECT ENAME FROM EMP WHERE ENAME LIKE '%S%' 
AND COMM IS NOT NULL 
AND COMM>4000
AND DEPTNO IN (10,30)
ORDER BY COMM DESC;
SELECT * FROM EMP WHERE  SAL BETWEEN 30000 AND 80000 AND HIREDATE ='10-APR-16';
SELECT * FROM EMP WHERE  SAL BETWEEN 30000 AND 80000 AND EXTRACT(YEAR FROM HIREDATE)>2016;
SELECT * FROM EMP WHERE JOB='SALESMAN'AND COMM <SAL+SAL*0.2 ORDER BY SAL ASC;
SELECT * FROM EMP WHERE EXTRACT(MONTH FROM HIREDATE) IN (6,7,8) AND SAL BETWEEN 30000 AND 70000;
SELECT * FROM EMP WHERE JOB<>'MANAGER'AND SAL>80000;
SELECT * FROM EMP WHERE JOB<>'MANAGER'AND SAL>80000;
SELECT SAL+COMM GROSS FROM EMP WHERE JOB='SALESMAN';
SELECT DISTINCT JOB FROM EMP;
SELECT SAL*12 "ANNUAL SAL" ,ENAME,SAL FROM EMP ORDER BY "ANNUAL SAL"  DESC,SAL ASC,ENAME DESC;
SELECT ENAME FROM EMP WHERE JOB IN('MANAGER','SALESMAN') AND ENAME LIKE'M%N' AND SAL+SAL*0.1>2500 AND JOB <> 'MANAGER' ORDER BY SAL DESC;
SELECT HIREDATE FROM EMP WHERE HIREDATE LIKE '%SEP%';
SELECT HIREDATE FROM EMP WHERE HIREDATE LIKE '%18';
select concat(concat(ename,' '),job) as result from emp where lower(ename) ='blake';

select ename,job,length(ename),instr(ename,'A') from emp where substr(job,1,5)=upper('sales');
SELECT ROUND(45.923,2), ROUND(45.923,0),ROUND(45.923,-1) ,ROUND(45.923,-2) FROM   DUAL;
SELECT 	TRUNC(45.923,2), TRUNC(45.923),TRUNC(45.923,-1) ,trunc(45.923,-2) FROM   DUAL;
SELECT	ename, sal, comm, MOD(sal, comm) FROM emp WHERE job = 'SALESMAN';

SELECT ename, (SYSDATE-hiredate)/7 WEEKS,ADD_MONTHS ('11-JAN-94',6)
,MONTHS_BETWEEN ('01-SEP-95','11-JAN-94'),NEXT_DAY ('01-SEP-95','FRIDAY'),LAST_DAY('01-SEP-95')
FROM   emp WHERE  deptno = 10;

SELECT UPPER(ENAME) FROM EMP;
SELECT ENAME FROM EMP WHERE SUBSTR(ENAME,1,1)='A' OR ENAME LIKE 'A%';
SELECT CONCAT(ENAME,CONCAT('-',JOB))  "hyphen separator" FROM EMP;
SELECT ENAME,INSTR(ENAME,'A') FROM EMP;
SELECT ENAME,ROUND(SAL,-2) FROM EMP;
SELECT ENAME,SAL,MOD(SAL,1000) FROM EMP;
SELECT UPPER(ENAME) FROM EMP;
SELECT ENAME FROM EMP WHERE SUBSTR(ENAME,1,1)='A' OR ENAME LIKE 'A%';
SELECT CONCAT(ENAME,CONCAT('-',JOB))  "hyphen separator" FROM EMP;
SELECT ENAME,INSTR(ENAME,'A') FROM EMP;
SELECT ENAME,ROUND(SAL,-2) FROM EMP;
SELECT ENAME,SAL,MOD(SAL,1000) FROM EMP;
SELECT ENAME,TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE),0) FROM EMP;
SELECT TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE)/12,0) FROM EMP WHERE TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE)/12,0)>30;
SELECT ENAME,NEXT_DAY(HIREDATE,'FRIDAY') FROM EMP;
SELECT ENAME,TO_CHAR(HIREDATE,'DD MM YYYY') FROM EMP;
SELECT TO_CHAR(SAL,'$99,999') FROM EMP;
SELECT TO_CHAR(TO_DATE('25-JUL-05','DD-MON-YYYY'),'DD-MON-YYYY') FROM DUAL;
SELECT ENAME,NVL(COMM,0) FROM EMP;
SELECT ENAME,(SAL*12)+NVL(COMM,0) FROM EMP;
SELECT ENAME,JOB,SAL,DECODE(JOB,'ANALYST',SAL+SAL*0.1,'CLERK',SAL+SAL*0.15,'MANAGER',SAL+SAL*0.12,SAL) AS NEW FROM EMP;
SELECT ENAME,NVL2(MGR,'HAS MANAGER', 'NO MANAGER') FROM EMP;
SELECT ENAME,NVL(TO_CHAR(MGR), 'NO MANAGER') FROM EMP;
SELECT LOWER(SUBSTR(ENAME,1,3)) FROM EMP;
SELECT ENAME,ROUND(HIREDATE,'MONTH') FROM EMP;
SELECT LOWER(ENAME),UPPER(ENAME),INITCAP(ENAME) FROM EMP;
SELECT ENAME FROM EMP WHERE LENGTH(ENAME)=5;
SELECT ENAME, INSTR(ENAME,'A') FROM EMP;
SELECT ENAME,SAL,ROUND(SAL,-2),TRUNC(SAL,-2) FROM EMP;
SELECT ENAME,SAL,NVL(COMM,0)/SAL*100 FROM EMP WHERE JOB='SALESMAN';
SELECT ENAME,TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE)/12,0),MOD(TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE)),12) FROM EMP;
SELECT EMPNO,ENAME,DEPTNO FROM EMP WHERE ENAME='BLAKE';
SELECT EMPNO,ENAME,DEPTNO FROM emp where LOWER(ename) = 'blake';
SELECT CONCAT(ENAME,CONCAT('-',EMPNO)) FROM EMP;
SELECT SUBSTR('STRING',1,3) FROM DUAL; //1 START 3 INDEX
SELECT LENGTH(' STRING ') FROM DUAL;
SELECT INSTR('STRING','R') FROM DUAL;// R PSOITION
SELECT TRIM('S' FROM 'S S MITH') FROM DUAL;
SELECT RTRIM(' SSMITH ') FROM DUAL;
SELECT REPLACE('TOY','Y','LET') FROM DUAL;
SELECT ENAME,CONCAT(ENAME,JOB),LENGTH(ENAME),INSTR(ENAME,'A') FROM EMP WHERE SUBSTR(JOB,1,5)='SALES';
SELECT MOD(1600,300) FROM DUAL;
SELECT ROUND(45.923,2), ROUND(45.923,0),ROUND(41.923,-2) FROM  DUAL;
SELECT ENAME,SAL,COMM,MOD(SAL,COMM) FROM EMP WHERE JOB='SALESMAN';
SELECT ENAME,(SYSDATE-HIREDATE)/7 WEEKS FROM EMP WHERE DEPTNO=10;
SELECT ENAME,TO_CHAR(HIREDATE,'FMDD MONTH YYYY') HIREDATE FROM EMP;
SELECT TO_CHAR(SAL,'$99,999') SALARY FROM EMP WHERE ENAME='SCOTT';
SELECT ENAME,SAL,COMM,(SAL*12)+NVL(COMM,0) FROM EMP;
SELECT ENAME,SAL,COMM, nvl2(comm,comm+sal-100,sal)  FROM EMP;
Select ename,length(ename),job,length(job),NULLIF(ename,job) from emp;
SELECT JOB,SAL, DECODE(JOB,'ANALYST',SAL+SAL*0.1,'CLERK',SAL*1.15,'MANAGER',SAL*1.20,SAL) FROM EMP;
